[package]
name = "day_2_part_2"
version = "0.1.0"
authors = ["Logan Konopatzke <logankono9080@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
